### ISSUE TITLE
Filename is not defined

### ISSUE THREAD

**Issue by BigWebstas** [rozahp/macupd_tracker#1]
In the error log i have a string of these :

> Err: exception occurred in handle(): global name 'filename' is not defined 

and the report does not update it just says the time and date, when i run it manually i get 

> Err: error in logfile
> Traceback (most recent call last):
>   File "reporter.py", line 300, in <module>
>     reporter.report()
>   File "reporter.py", line 219, in report
>     trackerDict=self.parse_tracker_files(trackerFiles)
>   File "reporter.py", line 146, in parse_tracker_files
>     row_dict=self.reporter_check_row(row)
>   File "reporter.py", line 61, in reporter_check_row
>     print "Err: error in logfile", filename, "- row:", row
> NameError: global name 'filename' is not defined

**Comment by rozahp** [comment]
Thanks for reporting this bug! It should have been solved now. Please check.

**Comment by rozahp** [comment]
Thanks for reporting this bug! It should have been solved now. Please check.
